server:
  port: 8100
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auction
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    template:
      default-topic: proposal-product-events
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: group_proposal
      auto-offset-reset: earliest
      properties:
        schema.registry.url: http://127.0.0.1:8085
        specific.avro.reader: true