name: CI/CD flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17 - auction-consumer
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: 'maven'

    - name: Build with Maven - auction-consumer
      working-directory: ./auction-consumer
      run: mvn clean install -DskipTests

    - name: Build & push Docker image - auction-consumer
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        directory: ./auction-consumer
        image: daiven75/auction-consumer
        tags: 1.0.0
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
