name: CI/CD flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: 'maven'

    - name: Build Services with Maven
      run: |
        cd ./auction-consumer
        mvn clean install -DskipTests

        cd ../auction-producer
        mvn clean install -DskipTests

        cd ../auction-service
        mvn clean install -DskipTests

    - name: Build and Push Services
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        cd ./auction-consumer
        docker build -t daiven75/auction-consumer:1.0.0 .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push daiven75/auction-consumer:1.0.0

        cd ../auction-producer
        docker build -t daiven75/auction-producer:1.0.0 .
        docker push daiven75/auction-producer:1.0.0

        cd ../auction-service
        docker build -t daiven75/auction-service:1.0.0 .
        docker push daiven75/auction-service:1.0.0
